---
trigger: none

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        repository: 'chatroom-moderator'
        buildContext: 'src/'
        command: 'build'
        Dockerfile: 'src/Dockerfile'
        tags: 'latest'