---
trigger: none

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker Build
      inputs:
        repository: 'chatroom-moderator'
        buildContext: 'src/'
        command: 'build'
        Dockerfile: 'src/Dockerfile'
        tags: 'latest'

    - task: ECRPushImage@1
      displayName: Pushing image to ECR repo
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        sourceImageName: 'chatroom-moderator'
        sourceImageTag: 'latest'
        repositoryName: '975049939172.dkr.ecr.ap-south-1.amazonaws.com/chatroom-moderator-test'
        pushTag: '$(Build.SourceVersion)'
        removeDockerImage: true