---
trigger: none

resources:
- repo: self

stages:
- stage: BuildAndPush
  displayName: Build and Push image to ECR
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          terraform plan

    - task: ManualIntervention@8
      displayName: Approve
      inputs:
        instructions: 'Terraform Plan executed. Approve to apply the changes.'

    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: 'aws s3 list'