---
trigger: none

resources:
- repo: self

stages:
- stage: PlanAndApply
  displayName: Terraform Plan and Apply
  jobs:
  - job: Plan
    displayName: Terraform Plan
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          ls -l
          cd iac
          terraform init
          terraform plan

  - job: Approval
    displayName: Approval
    dependsOn: Plan
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: Approve
      inputs:
        notifyUsers: 'santhoshpsk@outlook.com'
        instructions: 'Terraform Plan executed. Approve to apply the changes.'

  - job: ApplyChanges
    displayName: Apply Changes
    dependsOn: Approval
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          terraform init
          terraform apply -auto-approve