---
trigger: none

resources:
- repo: self

stages:
- stage: BuildAndPush
  displayName: Build and Push image to ECR
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          terraform init

    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          terraform plan

  - job: Approval
    displayName: Approval
    pool: server
    steps:
    - task: ManualValidation@0
      displayName: Approve
      inputs:
        notifyUsers: 'santhoshpsk@outlook.com'
        instructions: 'Terraform Plan executed. Approve to apply the changes.'

  - job: ApplyChanges
    displayName: Apply Changes
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AWSShellScript@1
      inputs:
        awsCredentials: 'aws-user'
        regionName: 'ap-south-1'
        scriptType: 'inline'
        inlineScript: |
          terraform init
          terraform apply -auto-approve